sudo: false
distro: trusty

language: python

python:
  - "3.6"

addons:
  apt:
    packages:
    - graphviz

install:
  - python3 -m pip install .

script:
  - seek-well run -p test_scripts -i init -r refresh -j hierarchy -u undefined -l fdp -g hierarchy
