sudo: false
distro: trusty

language: python

python:
  - "3.6"

env:
  global:
    - LANG=en.UTF-8
    - LC_ALL=en.UTF-8

install:
  - python3 -m pip install .

script:
  - seek-well run -p test_scripts -i init -r refresh -j hierarchy -l fdp -g hierarchy
