version: '3'

services:
  seek-well:
    build:
      context: .
      args:
        - PYTHON3_VERSION=${PYTHON3_VERSION}
    image: lycantropos/seek-well:0.2.1
    volumes:
      - ./test_scripts/:/opt/seek-well/test_scripts/
      - ./scripts/:/opt/seek-well/scripts/
      - ./README.md:/opt/seek-well/README.md
      - ./setup.py:/opt/seek-well/setup.py
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  # for debugging
    command:
      - run
      - -p
      - test_scripts
      - -i
      - init
      - -r
      - refresh
      - -j
      - hierarchy
      - -u
      - undefined
      - -l
      - fdp
      - -g
      - hierarchy
