version: '3'

services:
  seek-well:
    build:
      context: .
      args:
        - PYTHON3_VERSION=${PYTHON3_VERSION}
    image: lycantropos/seek-well:0.0.5
    volumes:
      - ./test_scripts:/seek-well/test_scripts
      - ./seek-well.py:/seek-well/seek-well.py
      - ./README.rst:/seek-well/README.rst
      - ./setup.py:/seek-well/setup.py
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  # for debugging
    command:
      - run
      - -p
      - test_scripts
      - -i
      - init
      - -r
      - refresh
      - -j
      - hierarchy
      - -l
      - fdp
      - -g
      - hierarchy
