CREATE TABLE t_table
(
  f_id                        BIGINT DEFAULT 0 PRIMARY KEY                 NOT NULL,
  f_server_id                 BIGINT DEFAULT 0                             NOT NULL,
  f_started_stamp             TIMESTAMP                                    NOT NULL,
  f_ended_stamp               TIMESTAMP                                    NOT NULL,
  f_game_type                 CHAR DEFAULT '' :: CHARACTER(1)              NOT NULL,
  f_name                      VARCHAR(255) DEFAULT '' :: CHARACTER VARYING NOT NULL,
  f_speed                     INTEGER DEFAULT 0                            NOT NULL,
  f_money_type                CHAR DEFAULT '' :: CHARACTER(1)              NOT NULL,
  f_pot_type                  CHAR DEFAULT '' :: CHARACTER(1)              NOT NULL,
  f_low_bet                   BIGINT DEFAULT 0                             NOT NULL,
  f_high_bet                  BIGINT DEFAULT 0                             NOT NULL,
  f_closed                    INTEGER DEFAULT 0                            NOT NULL,
  f_creator_id                BIGINT DEFAULT 0                             NOT NULL,
  f_permanent                 SMALLINT DEFAULT 0                           NOT NULL,
  f_protect                   SMALLINT DEFAULT 0                           NOT NULL,
  f_protection_password       VARCHAR(255) DEFAULT '' :: CHARACTER VARYING NOT NULL,
  f_created_stamp             TIMESTAMP                                    NOT NULL,
  f_tournament_id             BIGINT DEFAULT 0                             NOT NULL,
  f_num_seats                 INTEGER DEFAULT 0                            NOT NULL,
  f_use_for_balance           SMALLINT DEFAULT 0                           NOT NULL,
  f_use_for_jackpot           SMALLINT DEFAULT 0                           NOT NULL,
  f_tag                       VARCHAR(255) DEFAULT '' :: CHARACTER VARYING NOT NULL,
  f_require_player_tag        SMALLINT DEFAULT 0                           NOT NULL,
  f_template_table_id         BIGINT DEFAULT 0                             NOT NULL,
  f_force_disable_rake        SMALLINT DEFAULT 0                           NOT NULL,
  f_is_straddle_allowed       SMALLINT DEFAULT 0                           NOT NULL,
  f_num_restraddle_allowed    BIGINT DEFAULT 0                             NOT NULL,
  f_is_runittwice_allowed     SMALLINT DEFAULT 0                           NOT NULL,
  f_anonymous_table           SMALLINT DEFAULT 0                           NOT NULL,
  f_rake_table_name           VARCHAR(255) DEFAULT '' :: CHARACTER VARYING NOT NULL,
  f_fast_fold                 SMALLINT DEFAULT 0                           NOT NULL,
  f_use_group_activity_filter SMALLINT DEFAULT 0                           NOT NULL,
  f_ff_max_entries            BIGINT DEFAULT 4                             NOT NULL,
  f_ff_occupancy              BIGINT DEFAULT 50                            NOT NULL,
  f_ff_min_players            BIGINT DEFAULT 0                             NOT NULL
);
