CREATE TABLE t_tournament
(
  f_id                                                          BIGINT DEFAULT 0 PRIMARY KEY                        NOT NULL,
  f_name                                                        VARCHAR(255) DEFAULT '' :: CHARACTER VARYING        NOT NULL,
  f_state                                                       CHAR DEFAULT '' :: CHARACTER(1)                     NOT NULL,
  f_buy_in                                                      BIGINT DEFAULT 0                                    NOT NULL,
  f_start_date                                                  TIMESTAMP                                           NOT NULL,
  f_game_type                                                   CHAR DEFAULT '' :: CHARACTER(1)                     NOT NULL,
  f_money_type                                                  CHAR DEFAULT '' :: CHARACTER(1)                     NOT NULL,
  f_speed                                                       INTEGER DEFAULT 0                                   NOT NULL,
  f_level_time                                                  BIGINT DEFAULT 0                                    NOT NULL,
  f_break_time                                                  BIGINT DEFAULT 0                                    NOT NULL,
  f_break_period                                                BIGINT DEFAULT 0                                    NOT NULL,
  f_num_players                                                 BIGINT DEFAULT 0                                    NOT NULL,
  f_engager_id                                                  BIGINT DEFAULT 0                                    NOT NULL,
  f_pot_type                                                    CHAR DEFAULT '' :: CHARACTER(1)                     NOT NULL,
  f_tournament_type                                             CHAR DEFAULT '' :: CHARACTER(1)                     NOT NULL,
  f_max_players                                                 BIGINT DEFAULT 0                                    NOT NULL,
  f_created_stamp                                               TIMESTAMP                                           NOT NULL,
  f_creator_id                                                  BIGINT DEFAULT 0                                    NOT NULL,
  f_started_stamp                                               TIMESTAMP                                           NOT NULL,
  f_ended_stamp                                                 TIMESTAMP                                           NOT NULL,
  f_regular                                                     SMALLINT DEFAULT 0                                  NOT NULL,
  f_regular_period                                              BIGINT DEFAULT 0                                    NOT NULL,
  f_server_id                                                   BIGINT DEFAULT 0                                    NOT NULL,
  f_entry_fee                                                   BIGINT DEFAULT 0                                    NOT NULL,
  f_entry_fee_money_type                                        CHAR DEFAULT '' :: CHARACTER(1)                     NOT NULL,
  f_second_entry_fee_percent                                    BIGINT DEFAULT 0                                    NOT NULL,
  f_tables_seats                                                BIGINT DEFAULT 0                                    NOT NULL,
  f_initial_funds                                               BIGINT DEFAULT 0                                    NOT NULL,
  f_registration_date                                           TIMESTAMP                                           NOT NULL,
  f_listing_begin_date                                          TIMESTAMP                                           NOT NULL,
  f_listing_end_time                                            BIGINT DEFAULT 3600                                 NOT NULL,
  f_listing_cancel_time                                         BIGINT DEFAULT 3600                                 NOT NULL,
  f_min_players                                                 BIGINT DEFAULT 0                                    NOT NULL,
  f_play_time                                                   BIGINT DEFAULT 0                                    NOT NULL,
  f_seating_time                                                BIGINT DEFAULT 0                                    NOT NULL,
  f_private                                                     SMALLINT DEFAULT 0                                  NOT NULL,
  f_use_for_balance                                             SMALLINT DEFAULT 0                                  NOT NULL,
  f_admin_cancel                                                SMALLINT DEFAULT 0                                  NOT NULL,
  f_guaranteed_prize                                            BIGINT DEFAULT 0                                    NOT NULL,
  f_protection_password                                         VARCHAR(255) DEFAULT '' :: CHARACTER VARYING        NOT NULL,
  f_playing_time_limit                                          BIGINT DEFAULT 0                                    NOT NULL,
  f_parent_tournament_id                                        BIGINT DEFAULT 0                                    NOT NULL,
  f_num_selected_players                                        BIGINT DEFAULT 1                                    NOT NULL,
  f_min_player_level                                            BIGINT DEFAULT 0                                    NOT NULL,
  f_prize2_money_type                                           CHAR                                                NOT NULL,
  f_prize2_amount                                               BIGINT DEFAULT 0                                    NOT NULL,
  f_prize2_players                                              BIGINT DEFAULT 0                                    NOT NULL,
  f_comment                                                     VARCHAR(4096) DEFAULT '' :: CHARACTER VARYING       NOT NULL,
  f_prize2_distribution                                         CHAR DEFAULT 'S' :: CHARACTER(1)                    NOT NULL,
  f_special_prize                                               SMALLINT DEFAULT 0                                  NOT NULL,
  f_tag                                                         VARCHAR(255) DEFAULT '' :: CHARACTER VARYING        NOT NULL,
  f_require_player_tag                                          SMALLINT DEFAULT 0                                  NOT NULL,
  f_starting_blind_amount                                       BIGINT DEFAULT 0                                    NOT NULL,
  f_blind_increase_coeff                                        INTEGER DEFAULT 0                                   NOT NULL,
  f_prize_distribution                                          CHAR DEFAULT '' :: CHARACTER(1)                     NOT NULL,
  f_rebuy_allowed                                               SMALLINT DEFAULT 0                                  NOT NULL,
  f_rebuy2x_allowed                                             SMALLINT DEFAULT 0                                  NOT NULL,
  f_num_rebuy_allowed                                           BIGINT DEFAULT 0                                    NOT NULL,
  f_num_rebuy_time_limit                                        BIGINT DEFAULT 0                                    NOT NULL,
  f_num_rebuy_hi_threshold                                      BIGINT DEFAULT 0                                    NOT NULL,
  f_num_rebuy_chips_amount                                      BIGINT DEFAULT 0                                    NOT NULL,
  f_num_rebuy_chips_cost                                        BIGINT DEFAULT 0                                    NOT NULL,
  f_num_addon_allowed                                           SMALLINT DEFAULT 0                                  NOT NULL,
  f_num_addon_time_limit                                        BIGINT DEFAULT 0                                    NOT NULL,
  f_num_addon_chips_amount                                      BIGINT DEFAULT 0                                    NOT NULL,
  f_num_addon_chips_cost                                        BIGINT DEFAULT 0                                    NOT NULL,
  f_num_players_with_tickets                                    BIGINT DEFAULT 0                                    NOT NULL,
  f_late_registration_time_limit                                BIGINT DEFAULT 0                                    NOT NULL,
  f_num_players_not_participated                                BIGINT DEFAULT 0                                    NOT NULL,
  f_num_players_kicked                                          BIGINT DEFAULT 0                                    NOT NULL,
  f_ticket_distribution                                         CHAR DEFAULT 'F' :: CHARACTER(1)                    NOT NULL,
  f_ticket_price                                                BIGINT DEFAULT 0                                    NOT NULL,
  f_finish_late_registration_after_first_player_left_tournament SMALLINT DEFAULT 0                                  NOT NULL,
  f_finish_late_registration_after_bubble                       SMALLINT DEFAULT 0                                  NOT NULL,
  f_template_tournament_id                                      BIGINT DEFAULT 0                                    NOT NULL,
  f_shootout                                                    SMALLINT DEFAULT 0                                  NOT NULL,
  f_prize_table_name                                            VARCHAR(255) DEFAULT 'Default' :: CHARACTER VARYING NOT NULL,
  f_special_prize_description                                   VARCHAR(255) DEFAULT '' :: CHARACTER VARYING        NOT NULL,
  f_share_prize_enabled                                         SMALLINT DEFAULT 0                                  NOT NULL,
  f_owner_id                                                    BIGINT DEFAULT 0                                    NOT NULL,
  f_owner_guaranteed_prize_transaction_id                       BIGINT DEFAULT 0                                    NOT NULL,
  f_owner_prize2_transaction_id                                 BIGINT DEFAULT 0                                    NOT NULL,
  f_entry_method                                                CHAR DEFAULT '' :: CHARACTER(1)                     NOT NULL,
  f_ticket_template_id                                          BIGINT DEFAULT 0                                    NOT NULL,
  f_shadow_copy_prize_pool                                      BIGINT DEFAULT 0                                    NOT NULL,
  f_color_mark                                                  VARCHAR(255) DEFAULT '0' :: CHARACTER VARYING       NOT NULL,
  f_spin_prize_pool                                             BIGINT DEFAULT 0                                    NOT NULL,
  f_use_min_player_level_for_hide                               SMALLINT DEFAULT 0                                  NOT NULL
);
